export type Lang = 'fr' | 'ar'

export const t = (fr: string, ar: string, lang: Lang) => lang === 'ar' ? ar : fr

export const categories = [
  { id: 'dev', label: 'Développement', labelAr: 'البرمجة', icon: '💻', count: 342 },
  { id: 'data', label: 'Data & IA', labelAr: 'البيانات والذكاء الاصطناعي', icon: '📊', count: 218 },
  { id: 'design', label: 'Design', labelAr: 'التصميم', icon: '🎨', count: 156 },
  { id: 'security', label: 'Cybersécurité', labelAr: 'الأمن السيبراني', icon: '🔐', count: 97 },
  { id: 'business', label: 'Business', labelAr: 'الأعمال', icon: '📈', count: 184 },
  { id: 'cloud', label: 'Réseaux', labelAr: 'الشبكات', icon: '☁️', count: 129 },
  { id: 'lang', label: 'Langues', labelAr: 'اللغات', icon: '🌍', count: 88 },
  { id: 'marketing', label: 'Certifications', labelAr: 'الشهادات', icon: '📜', count: 112 },
]

export const platforms = [
  { id: 'udemy', name: 'Udemy', status: 'available', statusAr: 'متاح', color: '#A435F0' },
  { id: 'coursera', name: 'Coursera', status: 'available', statusAr: 'متاح', color: '#0056D2' },
  { id: 'htb', name: 'Hack The Box', status: 'available', statusAr: 'متاح', color: '#9FEF00', dark: true },
  { id: 'pluralsight', name: 'Pluralsight', status: 'on-request', statusAr: 'عند الطلب', color: '#F15B2A' },
  { id: 'linkedin', name: 'LinkedIn Learning', status: 'available', statusAr: 'متاح', color: '#0A66C2' },
  { id: 'datacamp', name: 'DataCamp', status: 'on-request', statusAr: 'عند الطلب', color: '#3B82F6', dark: true },
  { id: 'edx', name: 'edX', status: 'coming-soon', statusAr: 'قريباً', color: '#02262B' },
  { id: 'skillshare', name: 'Skillshare', status: 'coming-soon', statusAr: 'قريباً', color: '#00A88B' },
]

export const courses = [
  {
    id: '1',
    title: 'The Complete Python Bootcamp: Zero to Hero',
    titleAr: 'دورة بايثون الشاملة: من الصفر إلى الاحتراف',
    platform: 'Udemy',
    category: 'dev',
    level: 'Débutant',
    levelAr: 'مبتدئ',
    price_usd: 13.99,
    price_dzd: 1890,
    rating: 4.7,
    reviews: 453210,
    duration: '22h',
    instructor: 'Jose Portilla',
    image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400&h=220&fit=crop&auto=format',
    certificate: true,
    tag: 'Bestseller',
    tagColor: '#F59E0B',
  },
  {
    id: '2',
    title: 'AWS Certified Solutions Architect – Associate',
    titleAr: 'شهادة AWS المعتمدة - المهندس المعماري للحلول',
    platform: 'Udemy',
    category: 'cloud',
    level: 'Intermédiaire',
    levelAr: 'متوسط',
    price_usd: 13.99,
    price_dzd: 1890,
    rating: 4.8,
    reviews: 187650,
    duration: '27h',
    instructor: 'Stéphane Maarek',
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=220&fit=crop&auto=format',
    certificate: true,
    tag: 'Populaire',
    tagColor: '#3B82F6',
  },
  {
    id: '3',
    title: 'Machine Learning Specialization',
    titleAr: 'تخصص تعلم الآلة',
    platform: 'Coursera',
    category: 'data',
    level: 'Intermédiaire',
    levelAr: 'متوسط',
    price_usd: 49,
    price_dzd: 6620,
    rating: 4.9,
    reviews: 124800,
    duration: '3 mois',
    instructor: 'Andrew Ng',
    image: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=400&h=220&fit=crop&auto=format',
    certificate: true,
    tag: 'Certifiant',
    tagColor: '#3B82F6',
  },
  {
    id: '4',
    title: 'Certified Bug Bounty Hunter (CBBH)',
    titleAr: 'صائد الثغرات المعتمد (CBBH)',
    platform: 'Hack The Box',
    category: 'security',
    level: 'Avancé',
    levelAr: 'متقدم',
    price_usd: 490,
    price_dzd: 66150,
    rating: 4.8,
    reviews: 18900,
    duration: '6 mois',
    instructor: 'HTB Academy',
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=220&fit=crop&auto=format',
    certificate: true,
    tag: 'Certifiant',
    tagColor: '#3B82F6',
  },
  {
    id: '5',
    title: 'UI/UX Design Bootcamp',
    titleAr: 'معسكر تدريب تصميم واجهات المستخدم',
    platform: 'Udemy',
    category: 'design',
    level: 'Débutant',
    levelAr: 'مبتدئ',
    price_usd: 13.99,
    price_dzd: 1890,
    rating: 4.6,
    reviews: 78340,
    duration: '18h',
    instructor: 'Daniel Scott',
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=220&fit=crop&auto=format',
    certificate: false,
    tag: null,
    tagColor: null,
  },
  {
    id: '6',
    title: 'Google Data Analytics Professional Certificate',
    titleAr: 'شهادة محلل بيانات Google المهنية',
    platform: 'Coursera',
    category: 'data',
    level: 'Débutant',
    levelAr: 'مبتدئ',
    price_usd: 49,
    price_dzd: 6620,
    rating: 4.8,
    reviews: 296000,
    duration: '6 mois',
    instructor: 'Google',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=220&fit=crop&auto=format',
    certificate: true,
    tag: 'Nouveau',
    tagColor: '#3B82F6',
  },
]

export const orderStatuses = [
  { key: 'pending_payment', label: 'En attente de paiement', labelAr: 'في انتظار الدفع', color: '#F59E0B' },
  { key: 'payment_verif', label: 'Paiement en vérification', labelAr: 'التحقق من الدفع', color: 'var(--muted-foreground)' },
  { key: 'payment_confirmed', label: 'Paiement confirmé', labelAr: 'تأكيد الدفع', color: '#3B82F6' },
  { key: 'processing', label: 'Traitement en cours', labelAr: 'جاري المعالجة', color: '#3B82F6' },
  { key: 'action_required', label: 'Action client requise', labelAr: 'إجراء مطلوب من العميل', color: '#F59E0B' },
  { key: 'delivered', label: 'Livrée', labelAr: 'تم التسليم', color: '#3B82F6' },
  { key: 'cancelled', label: 'Annulée', labelAr: 'ملغاة', color: '#DC3545' },
  { key: 'refund_pending', label: 'Remboursement en cours', labelAr: 'استرداد جاري', color: 'var(--muted-foreground)' },
  { key: 'refunded', label: 'Remboursée', labelAr: 'تم الاسترداد', color: 'var(--muted-foreground)' },
  { key: 'dispute', label: 'Litige', labelAr: 'نزاع', color: '#DC3545' },
]

export const mockOrders = [
  {
    id: 'TGO-2024-0892',
    course: 'The Complete Python Bootcamp',
    platform: 'Udemy',
    amount: 1890,
    status: 'delivered',
    date: '14 Jan 2025',
    deliveryMethod: 'Accès compte personnel',
  },
  {
    id: 'TGO-2024-0756',
    course: 'AWS Certified Solutions Architect',
    platform: 'Udemy',
    amount: 1890,
    status: 'processing',
    date: '18 Jan 2025',
    deliveryMethod: 'Voucher officiel',
  },
  {
    id: 'TGO-2025-0031',
    course: 'Machine Learning Specialization',
    platform: 'Coursera',
    amount: 6620,
    status: 'payment_confirmed',
    date: '20 Jan 2025',
    deliveryMethod: 'Abonnement mensuel',
  },
]
